# Generated by Django 3.2.3 on 2021-05-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Общий рейтинг'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Moderated', 'Модерированная'), ('New', 'Новая')], default='New', max_length=200, verbose_name='Статус'),
        ),
    ]
