# Generated by Django 3.2.3 on 2021-05-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20210528_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [('view_all', 'View all')], 'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
    ]
