# Generated by Django 3.2.3 on 2021-05-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сессия'),
        ),
    ]
